application:
  locale:
    defaultLocale: en
    supportedLocales:
      - es
      - fr
      - it
      - en
      - de
      - nl
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32768/postgres
    schema:
    username: postgres
    password: docker
    driver: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
flyway:
  validateOnMigrate: true
  locations: classpath:/db/migration/{vendor}/