application:
  locale:
    defaultLocale: en
    supportedLocales:
      - es
      - fr
      - it
      - en
      - de
      - nl
spring:
  datasource:
    url: jdbc:postgresql://localhost:32770/postgres
    schema:
    username: postgres
    password: docker
    driver: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  flyway:
    enabled: true
flyway:
  validateOnMigrate: true
  locations: classpath:/db/migration/{vendor}/