application:
  locale:
    defaultLocale: en
    supportedLocales:
      - es
      - fr
      - it
      - en
      - de
      - nl
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
    driver: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
