application:
  locale:
    defaultLocale: en
    supportedLocales:
      - es
      - fr
      - it
      - en
      - de
      - nl
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32769/postgres
    schema:
    username: postgres
    password: docker
    driver: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
#   jpa:
#     hibernate:
#       ddl-auto: create-drop

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true